<script setup lang="ts">
import BrandIcon from './BrandIcon.vue'
const sections = [
  { title:'Get up and running.', icon:'play', label:'START HERE', links:[
    { title:'Getting started', text:'Install the app, check Java, and start a server.', href:'/guide/getting-started' },
    { title:'The desktop app', text:'Updates, data folders, and life outside the window.', href:'/guide/desktop' },
    { title:'Server software', text:'Understand the loaders and choose your setup.', href:'/reference/servers' },
  ] },
  { title:'Find your way around.', icon:'terminal', label:'MAKE IT YOURS', links:[
    { title:'The panel', text:'Your console, plugins, worlds, and backups.', href:'/guide/panel' },
    { title:'How it works', text:'The engine underneath your control room.', href:'/guide/how-it-works' },
    { title:'Command reference', text:'Every command, flag, and working example.', href:'/reference/commands' },
  ] },
  { title:'Keep things running.', icon:'shield', label:'GET A HAND', links:[
    { title:'Troubleshooting', text:'Recognize the error. Find the next step.', href:'/guide/troubleshooting' },
    { title:'Security & connections', text:'What stays local, and how friends can join.', href:'/guide/security' },
    { title:'Common questions', text:'Straight answers to the things people ask.', href:'/guide/faq' },
  ] },
]
</script>
<template>
  <main class="field-guide">
    <section class="field-intro">
      <div><span class="field-label">SPAWNLOFT / DOCUMENTATION</span><h1>Your world.<br><span>Your field guide.</span></h1><p>From your first server to your next big idea.<br> Find the steps, the tools, and the answers.</p><a class="field-primary" href="/guide/getting-started">Start your first server <BrandIcon name="arrow" :size="20" /></a></div>
      <nav class="quick-start" aria-label="Quick answers"><span class="field-label">WHAT BRINGS YOU HERE?</span><a href="/guide/getting-started"><span>01</span> I’m just getting started.<BrandIcon name="arrow" :size="19" /></a><a href="/guide/panel"><span>02</span> I want to do more.<BrandIcon name="arrow" :size="19" /></a><a href="/guide/troubleshooting"><span>03</span> Something needs a fix.<BrandIcon name="arrow" :size="19" /></a><p>Looking for something specific? Use Search in the navigation.</p></nav>
    </section>
    <section class="field-library" aria-labelledby="library-title"><div class="library-heading"><span class="field-label">THE LIBRARY</span><h2 id="library-title">A good place to find your feet.</h2><span>Guides & reference</span></div><div class="library-columns"><div v-for="section in sections" :key="section.title" class="library-column"><BrandIcon :name="section.icon" :size="35" /><span class="field-label">{{section.label}}</span><h3>{{section.title}}</h3><a v-for="link in section.links" :key="link.href" :href="link.href"><div><strong>{{link.title}}</strong><p>{{link.text}}</p></div><BrandIcon name="arrow" :size="18" /></a></div></div></section>
    <section class="field-panel"><div><span class="field-label">KNOW YOUR CONTROL ROOM</span><h2>Everything has<br> its place.</h2><p>Follow the console. Add a plugin. Take a backup. Get familiar with the panel you’ll use every day.</p><a href="/guide/panel">Take a look around <BrandIcon name="arrow" :size="19" /></a></div><a class="panel-capture" href="/guide/panel" aria-label="Explore the SpawnLoft panel"><img src="/img/tabs/console.webp" width="2558" height="1392" alt="The SpawnLoft desktop console, showing server controls and live logs." loading="lazy"><span>THE SPAWNLOFT APP / CONSOLE</span></a></section>
    <section class="field-next"><BrandIcon name="spark" :size="35" /><div><h2>Built in the open.</h2><p>See what’s new, follow what’s next, or help shape the app.</p></div><nav aria-label="Follow SpawnLoft"><a href="/changelog">Release notes <BrandIcon name="arrow" :size="16" /></a><a href="/roadmap">The roadmap <BrandIcon name="arrow" :size="16" /></a><a href="https://github.com/joogiebear/spawnloft/discussions">Join the conversation <BrandIcon name="external" :size="16" /></a></nav></section>
  </main>
</template>
<style scoped>
.field-guide { background:#090d0d; color:#efeee6; }.field-label { display:block; font:9px/1.7 var(--mono); letter-spacing:.12em; }.field-intro { max-width:1320px; margin:auto; padding:85px 5vw 90px; display:grid; grid-template-columns:1.4fr 1fr; gap:7vw; align-items:center; }.field-intro .field-label { color:#a0b28b; }h1 { font:600 clamp(48px,5.7vw,82px)/1.02 var(--display); letter-spacing:-.06em; margin:27px 0; }h1 span { color:#c4f566; }.field-intro p { color:#abb5a3; font-size:15px; line-height:1.8; }.field-primary { display:inline-flex; align-items:center; gap:30px; background:#c4f566; color:#090d0d; padding:15px 19px; font-size:13px; font-weight:600; margin-top:24px; }.field-primary:hover { background:#d7ff96; }.quick-start>.field-label { margin-bottom:23px; }.quick-start>a { display:flex; align-items:center; gap:20px; border-top:1px solid #a6ba9233; padding:24px 0; font:500 20px var(--display); letter-spacing:-.025em; }.quick-start>a>span { font:9px var(--mono); color:#91a17e; }.quick-start>a>svg { margin-left:auto; color:#c4f566; transition:transform .16s; }.quick-start>a:hover>svg { transform:translateX(5px); }.quick-start>p { font-size:11px; color:#849679; border-top:1px solid #a6ba9233; padding-top:20px; }
.field-library { background:#efeee6; color:#172016; padding:65px max(5vw,calc((100vw - 1188px)/2)) 80px; }.library-heading { display:flex; flex-wrap:wrap; align-items:baseline; gap:15px; padding-bottom:32px; border-bottom:1px solid #bbc4b1; }.library-heading>.field-label { width:100%; color:#5b6d4a; }.library-heading h2 { font:600 clamp(28px,3vw,42px)/1.1 var(--display); letter-spacing:-.045em; margin:0; }.library-heading>span:last-child { margin-left:auto; font-size:11px; color:#6b775f; }.library-columns { display:grid; grid-template-columns:repeat(3,1fr); gap:45px; }.library-column { padding-top:37px; }.library-column>svg { color:#406722; margin-bottom:24px; }.library-column>.field-label { font-size:8px; color:#68775a; }.library-column h3 { font:600 27px/1.2 var(--display); letter-spacing:-.04em; margin:11px 0 26px; }.library-column a { display:flex; align-items:center; gap:12px; padding:21px 0; border-top:1px solid #c5ccbd; }.library-column a>div { flex:1; }.library-column strong { font-size:14px; font-weight:600; }.library-column p { font-size:12px; line-height:1.65; color:#67715f; margin:8px 0 0; max-width:270px; }.library-column a>svg { color:#496c2b; transition:transform .16s; }.library-column a:hover>svg { transform:translateX(4px); }.library-column a:hover strong { text-decoration:underline; text-underline-offset:4px; }
.field-panel { max-width:1320px; margin:auto; padding:85px 5vw; display:grid; grid-template-columns:.8fr 1.4fr; gap:7vw; align-items:center; }.field-panel .field-label { color:#a0b28b; }.field-panel h2 { font:500 clamp(38px,4.4vw,60px)/1.05 var(--display); letter-spacing:-.05em; margin:24px 0; }.field-panel p { color:#a0ae94; font-size:14px; line-height:1.8; }.field-panel>div>a { display:inline-flex; gap:24px; align-items:center; color:#c4f566; font-size:12px; margin-top:22px; }.panel-capture img { width:100%; display:block; border:1px solid #4a5d38; }.panel-capture span { display:block; font:8px var(--mono); color:#8e9d81; letter-spacing:.1em; margin-top:16px; }.field-next { background:#c4f566; color:#16220d; padding:45px max(5vw,calc((100vw - 1188px)/2)); display:flex; gap:28px; align-items:center; }.field-next h2 { font:600 33px var(--display); letter-spacing:-.045em; margin:0 0 8px; }.field-next p { font-size:13px; color:#47632f; margin:0; }.field-next nav { margin-left:auto; display:grid; gap:13px; }.field-next a { display:flex; align-items:center; justify-content:space-between; gap:25px; font-size:12px; }.field-next a:hover { text-decoration:underline; }.field-guide a:focus-visible { outline:2px solid #83a945; outline-offset:6px; }
@media(max-width:900px) { .field-intro { gap:35px; }.quick-start>a { font-size:17px; gap:12px; }.library-columns { gap:25px; }.library-column h3 { font-size:23px; }.field-next>svg { display:none; } }
@media(max-width:650px) { .field-intro { padding:48px 22px; grid-template-columns:1fr; gap:45px; }h1 { font-size:49px; }.field-intro p { font-size:13px; }.quick-start>a { font-size:21px; }.field-library { padding:43px 22px; }.library-heading h2 { font-size:33px; }.library-heading>span:last-child { margin:0; }.library-columns { grid-template-columns:1fr; gap:15px; }.library-column { padding-top:25px; }.library-column>svg { float:right; margin:0; }.library-column h3 { font-size:29px; margin-bottom:22px; }.library-column a { padding:18px 0; }.library-column p { max-width:none; }.field-panel { padding:50px 22px; grid-template-columns:1fr; gap:32px; }.field-panel h2 { font-size:43px; }.field-next { padding:35px 22px; display:block; }.field-next nav { margin-top:30px; gap:20px; }.field-next h2 { font-size:32px; } }
@media(prefers-reduced-motion:reduce) { .quick-start>a>svg,.library-column a>svg { transition:none; } }
</style>
